version: '3'

services:
  mongo:
    image: mongo:latest
    command: mongod --auth
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongodb_data_container:
