export const timezones = [
  { label: 'International Date Line West (UTC-12:00)', value: 'Pacific/Midway' },
  { label: 'Samoa Standard Time (UTC-11:00)', value: 'Pacific/Samoa' },
  { label: 'Hawaii-Aleutian Standard Time (UTC-10:00)', value: 'Pacific/Honolulu' },
  { label: 'Alaska Standard Time (UTC-09:00)', value: 'America/Anchorage' },
  { label: 'Pacific Standard Time (UTC-08:00)', value: 'America/Los_Angeles' },
  { label: 'Mountain Standard Time (UTC-07:00)', value: 'America/Denver' },
  { label: 'Central Standard Time (UTC-06:00)', value: 'America/Chicago' },
  { label: 'Eastern Standard Time (UTC-05:00)', value: 'America/New_York' },
  { label: 'Atlantic Standard Time (UTC-04:00)', value: 'America/Halifax' },
  { label: 'Newfoundland Standard Time (UTC-03:30)', value: 'America/St_Johns' },
  { label: 'Brasília Standard Time (UTC-03:00)', value: 'America/Sao_Paulo' },
  { label: 'Argentina Standard Time (UTC-03:00)', value: 'America/Argentina/Buenos_Aires' },
  { label: 'Greenland Standard Time (UTC-03:00)', value: 'America/Godthab' },
  { label: 'Mid-Atlantic Standard Time (UTC-02:00)', value: 'Atlantic/South_Georgia' },
  { label: 'Azores Standard Time (UTC-01:00)', value: 'Atlantic/Azores' },
  { label: 'Greenwich Mean Time (UTC+00:00)', value: 'Etc/GMT' },
  { label: 'Central European Standard Time (UTC+01:00)', value: 'Europe/Berlin' },
  { label: 'Eastern European Standard Time (UTC+02:00)', value: 'Europe/Helsinki' },
  { label: 'Moscow Standard Time (UTC+03:00)', value: 'Europe/Moscow' },
  { label: 'Pakistan Standard Time (UTC+05:00)', value: 'Asia/Karachi' },
  { label: 'India Standard Time (UTC+05:30)', value: 'Asia/Kolkata' },
  { label: 'Nepal Standard Time (UTC+05:45)', value: 'Asia/Kathmandu' },
  { label: 'Bangladesh Standard Time (UTC+06:00)', value: 'Asia/Dhaka' },
  { label: 'Myanmar Standard Time (UTC+06:30)', value: 'Asia/Yangon' },
  { label: 'Indochina Time (UTC+07:00)', value: 'Asia/Bangkok' },
  { label: 'China Standard Time (UTC+08:00)', value: 'Asia/Shanghai' },
  { label: 'Japan Standard Time (UTC+09:00)', value: 'Asia/Tokyo' },
  { label: 'Australian Central Standard Time (UTC+09:30)', value: 'Australia/Darwin' },
  { label: 'Australian Eastern Standard Time (UTC+10:00)', value: 'Australia/Sydney' },
  { label: 'Lord Howe Standard Time (UTC+10:30)', value: 'Australia/Lord_Howe' },
  { label: 'New Zealand Standard Time (UTC+12:00)', value: 'Pacific/Auckland' },
  { label: 'Tonga Standard Time (UTC+13:00)', value: 'Pacific/Tongatapu' },
]
